### ISSUE TITLE
Delphi Grammar

### ISSUE THREAD

**Issue by DGH2112** [MHumm/DelphiGrammar#1]
https://github.com/DGH2112/Browse-and-Doc-It/blob/master/Documentation/Grammar%20Files%20(BNF)/Object%20Pascal%20Grammar.bnf

**Comment by MHumm** [comment]
Thanks for pointing me to it. I started discussion now thether this repo here makes sensoe or better contribution to your started one. As you can see I filed an issue already in yours ;-)

**Comment by DGH2112** [comment]
I've loaded my grammar files.
I'll close this issue.
